baseURL = 'https://mukii.space/'
languageCode = 'en-us'
title = 'MUKIMASTA'
mainSections = []

theme = 'dario'

[markup.goldmark.renderer]
hardWraps = true
relativeURLs = true

[markup.goldmark.extensions.passthrough]
enable = true
[markup.goldmark.extensions.passthrough.delimiters]
block = [['$$', '$$']]
inline = [['$', '$']]
